name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: pnpm install
    - name: Install Playwright Browsers
      run: pnpm dlx playwright install --with-deps
    - name: Add hosts to /etc/hosts
      run: |
          sudo echo "127.0.0.1 test.localhost" | sudo tee -a /etc/hosts
    - name: Start test dependencies
      run: |
          make start-test-servers
    - name: Run Playwright tests
      run: pnpm dlx playwright test
    - name: Kill test dependencies
      run: |
          make kill-test-servers
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
