name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Install pnpm
      run: npm i -g pnpm
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
    - name: Install Playwright Browsers
      run: pnpm dlx playwright install --with-deps
    - name: Add hosts to /etc/hosts
      run: |
          sudo echo "127.0.0.1 test.localhost" | sudo tee -a /etc/hosts
    - name: Build client and server
      run: |
          go build -ldflags="-s -w" -o beaver ./cmd/beaver_client
          go build -ldflags="-s -w" -o beaver_server ./cmd/beaver_server
          go build -ldflags="-s -w" -o test_server ./e2e/server.go
    - name: Start test servers
      run: |
          ./test_server &
          sleep 5
          ./beaver_server --config docs/beaver_server.yaml &
          sleep 5
    - name: Start test client
      run: |
          ./beaver --config docs/beaver_client.yaml --port 9999 --subdomain test &
          sleep 3
    - name: Run Playwright tests
      run: pnpm dlx playwright test
    - name: Kill test servers
      run: |
          make kill-test-servers
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
